# azure-pipelines.yml

trigger:
- master

resources:
- repo: self

variables:
  tag: 'azuredevops-$(Build.BuildNumber)'
  imageName: '121456782pen/container-scanning-demo'
  vmImageName: 'ubuntu-latest'
  imageRepository: 'vossec'
  dockerRegistryServiceConnection: 'ACR'
  

stages:
  - stage: Build
    displayName: 'Build docker Container'
    jobs:
    - template: templates/build-docker.yml
    
  - stage: Test
    displayName: 'Snyk Application Security Scanning'
    dependsOn: Build
    jobs:
    - template: templates/snyk-app-scan.yml
    
  - stage: Test
    displayName: 'Trivy Docker Security Scanning'
    dependsOn: Build
    jobs:
    - template: templates/trivy-security-scan.yml
