# azure-pipelines.yml

trigger:
- master

resources:
- repo: self

variables:
  tag: 'azuredevops-$(Build.BuildNumber)'
  imageName: '121456782pen/container-security-scanning'
  dockerRegistryServiceConnection: 'Dockerhub'
  trivyVersion: 0.12.0



stages:
  - stage: build
    jobs:
    - job: Snyk_App_Scan
      steps:
      - template: templates/snyk-app-scan.yml
    - job: build_security_scan_container
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - template: templates/build-docker.yml
      - template: templates/trivy-security-scan.yml
 

  
#  - template: templates/snyk-container-scan.yml
  
#  - template: templates/dockle-container.yml
    
