# azure-pipelines.yml

trigger:
- master

resources:
- repo: self

variables:
  tag: 'azuredevops-$(Build.BuildNumber)'
  imageName: '121456782pen/container-security-scanning'
  dockerRegistryServiceConnection: 'Dockerhub'
  trivyVersion: 0.12.0

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: templates/build-docker.yml
    displayName: 'Build docker Container'
    
  - template: templates/trivy-security-scan.yml
    displayName: 'Trivy Docker Security Scanning'
    dependsOn: Build
    
