# azure-pipelines.yml

trigger:
- master

resources:
- repo: self

variables:
  tag: 'azuredevops-$(Build.BuildNumber)'
  imageName: '121456782pen/container-security-scanning'
  dockerRegistryServiceConnection: 'Dockerhub'
  trivyVersion: 0.12.0

pool:
  vmImage: 'ubuntu-latest'
  
jobs:
- template: templates/build-docker.yml
    
#- template: templates/trivy-security-scan.yml

#- template: templates/snyk-app-scan.yml
  
#- template: templates/snyk-container-scan.yml
  
#- template: templates/dockle-container.yml
    
