jobs:
- job: 'Docker_Build'
  steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      containerRegistry: 'Dockerhub'
      repository: '$(imageName)'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: '$(tag)'

